# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            OMHacker作业
tagline:          'OMHacker作业'
description:      '已经有个hexo博客了，这个是为了交作业'
url:              http://homework.complexly.me
baseurl:          /

author:
  name:           'ComplexLY'
  url:            http://homework.complexly.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/complexly/homework

kramdown:
  input:GFM