# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Blog 2
tagline:          'ComplexLY的OMHacker作业'
description:      '已经有个hexo博客了，这个是为了交作业'
url:              http://homework.complexly.me
baseurl:          /

author:
  name:           'ComplexLY'
  url:            http://homework.complexly.me

paginate:         5

# Custom vars

kramdown:
  input:GFM